export const guides=[
 {slug:'choosing-a-public-api',title:'How to choose a public API for your project',description:'A practical checklist for comparing API access, limits, data rights, browser support, and maintenance.',label:'START HERE',intro:'Start with the feature you need, then evaluate the conditions that could prevent you from shipping it. A working sample request is only the first step.',sections:[
 {title:'Define the data you actually need',text:'Write down the fields, geographic coverage, update frequency, and historical depth your feature requires. A current-weather API and a historical-climate API can sit in the same category but solve different problems. Use a representative sample rather than assuming every record has the same shape.'},
 {title:'Separate free access from production permission',text:'No API key means the listed endpoint does not require a private credential. It does not promise unlimited requests, commercial permission, or rights to redistribute the results. Look for quotas, attribution, caching rules, and terms for the specific plan you will use.'},
 {title:'Check the integration environment',text:'A request that works in a terminal may fail in a browser because of CORS. Server credentials should stay on your server in a production app. Endpoint’s browser playground is useful for direct tests with limited test credentials, but it cannot make a provider support browser requests.'},
 {title:'Test failure as well as success',text:'Try an empty search, a missing record, and a documented invalid parameter using non-sensitive data. Handle HTTP errors, unexpected content types, empty arrays, and rate-limit responses. Decide what your interface will show when the provider is unavailable.'},
 {title:'Choose based on evidence',text:'Record the official documentation URL, the date you reviewed it, and the conditions you confirmed. Keep an exit plan: isolate provider-specific logic so you can change services later. Our reviewed guides identify documentation checks; community listings are discovery leads that still need verification.'}],table:{headers:['Question','What to confirm'],rows:[['Can I ship this?','Commercial use, attribution, and redistribution rights'],['Will it fit my traffic?','Daily quotas, burst limits, and overage costs'],['Will it run in my app?','Authentication and CORS for your exact origin'],['Can I rely on the data?','Coverage, freshness, missing fields, and units']]},sources:[['Google: helpful, reliable content','https://developers.google.com/search/docs/fundamentals/creating-helpful-content'],['MDN: using Fetch','https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch']]},
 {slug:'browser-api-requests-and-cors',title:'Why an API request works in cURL but fails in a browser',description:'Understand browser CORS, preflight requests, exposed response headers, and how to interpret network errors in the API playground.',label:'BROWSER REQUESTS',intro:'Browsers enforce cross-origin access rules that terminal clients do not. The provider must allow your website’s origin before browser JavaScript can read its response.',sections:[
 {title:'What CORS changes',text:'Cross-Origin Resource Sharing (CORS) is a provider-controlled policy expressed in HTTP response headers. For a simple request, the browser may send it but prevent your code from reading the response. A failed browser fetch therefore does not prove that the API is offline or that the request had no effect.'},
 {title:'Why adding authentication can trigger a preflight',text:'An Authorization header, a custom API-key header, or an application/json body can cause the browser to send an OPTIONS preflight first. The provider must permit the origin, method, and requested headers. A successful unauthenticated GET does not guarantee that authenticated requests will work.'},
 {title:'Why there is no “disable CORS” switch here',text:'Setting fetch mode to no-cors produces an opaque response that JavaScript cannot inspect. Adding Access-Control-Allow-Origin to your request does not grant permission; it is a response header controlled by the provider. Endpoint does not route requests through a proxy to bypass this policy.'},
 {title:'Interpret errors carefully',text:'Browser fetch often reports the same generic network error for CORS, DNS, TLS, offline connections, extensions, and blocked redirects. Open your browser’s Network panel to inspect the failing request and consult the provider’s browser guidance. This playground blocks redirects to avoid forwarding an authenticated request to another destination.'},
 {title:'What you can inspect',text:'When a request succeeds, the response panel shows status, duration, size, and browser-visible headers. Some headers remain hidden unless the provider explicitly exposes them. JSON can be explored as a tree or table; other text stays plain text, including HTML, to avoid running remote markup.'}],sources:[['MDN: Cross-Origin Resource Sharing','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS'],['MDN: Fetch API','https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch']]},
 {slug:'api-authentication',title:'API keys, bearer tokens, and Basic authentication explained',description:'Choose the correct authentication method for a browser API test, and understand what happens to your credentials.',label:'AUTHENTICATION',intro:'Use the exact authentication scheme documented by the provider. An API key, an OAuth access token, and a username/password pair are not interchangeable.',sections:[
 {title:'API keys in headers or query parameters',text:'Some providers expect a custom header such as X-API-Key; others require a named query parameter. Match both the parameter name and location. Query credentials can appear in the provider’s access logs. In Endpoint, request URLs stay out of the address bar and are not saved to browser storage.'},
 {title:'Bearer tokens and OAuth',text:'A bearer token is sent using the Authorization: Bearer header. Anyone who possesses it may be able to use its permissions. The playground accepts an existing access token; it does not run an OAuth login or refresh-token flow. Obtain an appropriately scoped test token using the provider’s own process.'},
 {title:'Basic authentication',text:'Basic authentication encodes a username and password into an Authorization header; Base64 is not encryption. Use HTTPS and follow the provider’s credential rules. Browser access still depends on the provider permitting the Authorization header through CORS.'},
 {title:'How credentials are handled here',text:'The request editor keeps values in the current page’s memory and sends them directly to your chosen HTTPS API endpoint only when you press Send request. It does not use an Endpoint backend, cookies, local storage, or session storage for credentials. Leaving or reloading the page clears the editor; browser extensions and the receiving provider are outside Endpoint’s control.'},
 {title:'Copy examples without accidentally sharing secrets',text:'Code previews replace authentication values with placeholders by default. Custom headers and query values are also hidden in the default preview. Reveal values only when needed, and check copied snippets before sharing them. Response data can itself be sensitive and is shown as returned.'}],sources:[['MDN: HTTP authentication','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Authentication'],['MDN: Authorization header','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Authorization']]}
];
