import {filterCatalog,escapeHTML as e} from '../lib/library-state.mjs';
const grid=document.querySelector('#api-grid');
if(grid){
 const $=s=>document.querySelector(s),base=grid.dataset.base;
 let catalog=null,ready=null,state={q:'',reviewed:false,noKey:false,free:false,sort:'curated',page:Number(grid.dataset.initialPage)};
 function readState(){const q=new URLSearchParams(location.search);state={q:q.get('q')||'',reviewed:q.get('reviewed')==='1',noKey:q.get('noKey')==='1',free:q.get('free')==='1',sort:q.get('sort')==='name'?'name':'curated',page:Number(q.get('page'))||Number(location.pathname.match(/\/page\/(\d+)\//)?.[1])||1};$('#search').value=state.q;$('#filter-reviewed').checked=state.reviewed;$('#filter-no-key').checked=state.noKey;$('#filter-free').checked=state.free;$('#sort').value=state.sort;}
 async function load(){if(catalog)return;if(ready)return ready;$('#library-status').textContent='Loading the searchable catalog…';ready=fetch('/catalog.json').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{const slugs=grid.dataset.slugs?new Set(JSON.parse(grid.dataset.slugs)):null;catalog=slugs?data.filter(a=>slugs.has(a.slug)):data;$('#library-status').textContent='';}).catch(()=>{$('#library-status').textContent='Search could not load. Try again, or use the category and page links below.';ready=null;throw new Error('Catalog unavailable');});return ready;}
 function url(page=state.page){const q=new URLSearchParams();if(state.q)q.set('q',state.q);if(state.reviewed)q.set('reviewed','1');if(state.noKey)q.set('noKey','1');if(state.free)q.set('free','1');if(state.sort!=='curated')q.set('sort',state.sort);if(page>1)q.set('page',String(page));return base+(q.size?'?'+q:'');}
 function render(sync=true){const result=filterCatalog(catalog,state);state.page=result.page;grid.innerHTML=result.items.map(a=>`<article class="api-card"><div class="card-top"><span class="api-mark ${e(a.color)}" aria-hidden="true">${e(a.mark)}</span><span class="review-tag ${a.review==='reviewed'?'is-reviewed':''}">${a.review==='reviewed'?'Docs reviewed':a.tested?'Tested example':'Community listing'}</span></div><div class="card-copy"><span class="small-label">${e(a.category)}</span><h3><a href="/apis/${encodeURIComponent(a.slug)}/">${e(a.name)}<span aria-hidden="true">↗</span></a></h3><p>${e(a.description)}</p></div><div class="card-meta"><span class="auth-tag ${a.auth==='No key'?'no-key':''}">${a.review==='catalog'&&!a.tested?'Reported: ':''}${e(a.auth)}</span><span>${e(a.plan)}</span></div></article>`).join('');$('#empty-results').hidden=result.total>0;$('#result-summary').textContent=result.total?`Showing ${(state.page-1)*36+1}–${Math.min(state.page*36,result.total)} of ${result.total.toLocaleString()} APIs`:'0 APIs found';const nums=[...new Set([1,result.pages,...Array.from({length:5},(_,i)=>state.page+i-2).filter(n=>n>0&&n<=result.pages)])].sort((a,b)=>a-b);let links=[];const link=(n,text,label='')=>`<a href="${e(url(n))}" data-page="${n}" ${n===state.page?'aria-current="page"':''} ${label?`aria-label="${label}"`:''}>${text}</a>`;if(state.page>1)links.push(link(state.page-1,'←','Previous page'));nums.forEach((n,i)=>{if(i&&n-nums[i-1]>1)links.push('<span>…</span>');links.push(link(n,n));});if(state.page<result.pages)links.push(link(state.page+1,'→','Next page'));$('#pagination').innerHTML=result.total?links.join(''):'';if(sync)history.replaceState(null,'',url());}
 async function change(){state.q=$('#search').value;state.reviewed=$('#filter-reviewed').checked;state.noKey=$('#filter-no-key').checked;state.free=$('#filter-free').checked;state.sort=$('#sort').value;state.page=1;try{await load();render();}catch{}}
 let timer;$('#search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(change,150);});$('#library-search').addEventListener('submit',ev=>{ev.preventDefault();clearTimeout(timer);change();});['#filter-reviewed','#filter-no-key','#filter-free','#sort'].forEach(s=>$(s).addEventListener('change',change));
 $('#pagination').addEventListener('click',async ev=>{const a=ev.target.closest('a[data-page]');if(!a||ev.metaKey||ev.ctrlKey)return;ev.preventDefault();try{await load();state.page=Number(a.dataset.page);render();$('#result-summary').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}catch{location.href=a.href;}});
 $('#reset-search').addEventListener('click',()=>{$('#search').value='';$('#filter-reviewed').checked=false;$('#filter-no-key').checked=false;$('#filter-free').checked=false;$('#sort').value='curated';change();});
 $('#category-search').addEventListener('input',ev=>document.querySelectorAll('.category-list a').forEach(a=>a.hidden=!a.textContent.toLowerCase().includes(ev.target.value.toLowerCase())));
 document.addEventListener('keydown',ev=>{if(ev.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){ev.preventDefault();$('#search').focus();}});
 window.addEventListener('popstate',async()=>{readState();try{await load();render(false);}catch{}});
 readState();if(location.search)load().then(()=>render(false)).catch(()=>{});
}
