import {buildRequest,snippets,readLimited,tableData} from '../lib/request.mjs';
const root=document.querySelector('.playground');
if(root){
 const $=s=>root.querySelector(s),examples=JSON.parse($('#playground-examples').textContent);
 let controller=null,responseData=null,view='tree',language='curl',codes=null,timedOut=false;
 function row(container,key='',value=''){
  const div=document.createElement('div');div.className='key-value-row';
  const k=document.createElement('input');k.placeholder='Name';k.setAttribute('aria-label','Parameter or header name');k.value=key;k.autocomplete='off';k.spellcheck=false;
  const v=document.createElement('input');v.placeholder='Value';v.setAttribute('aria-label','Parameter or header value');v.value=value;v.autocomplete='off';v.spellcheck=false;
  const del=document.createElement('button');del.type='button';del.textContent='×';del.setAttribute('aria-label','Remove '+(key||'row'));del.addEventListener('click',()=>{div.remove();preview();});div.append(k,v,del);$(container).append(div);
 }
 const rows=s=>[...$(s).children].map(r=>[r.children[0].value,r.children[1].value]);
 function input(){return {url:$('#request-url').value,method:$('#request-method').value,params:rows('#request-params'),headers:rows('#request-headers'),auth:{type:$('#auth-type').value,name:$('#auth-name').value,value:$('#auth-value').value,username:$('#auth-user').value},body:$('#request-body').value,bodyType:$('#body-type').value,confirmed:$('#confirm-mutation').checked};}
 function authUI(){const type=$('#auth-type').value;$('#auth-fields').hidden=type==='none';$('#auth-name-wrap').hidden=!['query','header'].includes(type);$('#auth-user-wrap').hidden=type!=='basic';$('#auth-value-label').textContent=type==='basic'?'Password':type==='bearer'?'Access token':'API key';}
 function preview(){authUI();$('#body-section').hidden=['GET','HEAD'].includes($('#request-method').value);try{const r=buildRequest(input(),{preview:true,reveal:$('#reveal-values').checked});codes=snippets(r);$('#request-code').textContent=codes[language];$('#request-destination').textContent='Sends directly to '+new URL(r.url).hostname;$('#copy-request').disabled=false;}catch(error){codes=null;$('#request-code').textContent=error.message;$('#copy-request').disabled=true;$('#request-destination').textContent='Choose a valid HTTPS endpoint.';}}
 function resetResponse(){responseData=null;$('#download-response').disabled=true;$('#response-meta').replaceChildren();const p=document.createElement('span');p.className='status-pill';p.textContent='Ready when you are';$('#response-meta').append(p);$('#response-content').replaceChildren();const d=document.createElement('div');d.className='response-placeholder';const h=document.createElement('h3');h.textContent='Your response will appear here.';const t=document.createElement('p');t.textContent='Nothing runs until you press Send request.';d.append(h,t);$('#response-content').append(d);}
 function loadExample(slug){$('#request-params').replaceChildren();$('#request-headers').replaceChildren();$('#auth-type').value='none';$('#auth-value').value='';$('#auth-name').value='';$('#auth-user').value='';$('#request-body').value='';$('#request-method').value='GET';$('#reveal-values').checked=false;$('#confirm-mutation').checked=false;$('#request-error').hidden=true;resetResponse();const a=examples.find(x=>x.slug===slug);$('#request-example').value=a?slug:'custom';$('#example-docs').hidden=!a&&!root.dataset.docs;if(!a&&root.dataset.docs)$('#example-docs').href=root.dataset.docs;$('#request-url').value='';if(a){$('#example-docs').href=a.docs;const u=new URL(a.url);for(const [k,v]of u.searchParams){if(/YOUR_API_KEY/i.test(v)){$('#auth-type').value='query';$('#auth-name').value=k;}else row('#request-params',k,v);}u.search='';$('#request-url').value=u.href;for(const [k,v]of Object.entries(a.headers)){if(k.toLowerCase()==='authorization'&&v.toLowerCase().startsWith('bearer ')){$('#auth-type').value='bearer';}else if(/^YOUR_API_KEY$/.test(v)){$('#auth-type').value='header';$('#auth-name').value=k;}else row('#request-headers',k,v);}}preview();}
 $('#add-param').addEventListener('click',()=>{row('#request-params');preview();});$('#add-header').addEventListener('click',()=>{row('#request-headers');preview();});
 $('#request-form').addEventListener('input',preview);$('#request-form').addEventListener('change',preview);$('#reveal-values').addEventListener('change',preview);
 $('#request-example').addEventListener('change',()=>loadExample($('#request-example').value));$('#clear-request').addEventListener('click',()=>{controller?.abort();loadExample('custom');});
 root.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>{language=b.dataset.code;root.querySelectorAll('[data-code]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));preview();}));
 $('#copy-request').addEventListener('click',async()=>{if(!codes)return;try{await navigator.clipboard.writeText(codes[language]);$('#copy-status').textContent=$('#reveal-values').checked?'Copied with entered values. Check for secrets before sharing.':'Copied with values replaced by placeholders.';}catch{$('#copy-status').textContent='Clipboard access is unavailable. Select the code and copy it manually.';}});
 function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(className)n.className=className;return n;}
 function valueNode(v){const type=v===null?'null':typeof v;let text=typeof v==='string'?JSON.stringify(v):JSON.stringify(v);if(text===undefined)text='undefined';return node('span',text.length>1000?text.slice(0,1000)+'…':text,'json-'+type);}
 function tree(value,key='$',depth=0,budget={remaining:600}){if(--budget.remaining<0)return node('p','More values available in the JSON or raw view.','field-help');if(value===null||typeof value!=='object'){const line=node('div',undefined,'json-leaf');line.append(node('span',key+': ','json-key'),valueNode(value));return line;}const entries=Object.entries(value);const d=node('details',undefined,'json-node');d.open=depth<2;const summary=node('summary');summary.append(node('span',key,'json-key'),node('span',Array.isArray(value)?` [${entries.length} items]`:` {${entries.length} keys}`,'json-count'));d.append(summary);if(depth>=10){d.append(node('p','Nested data continues in the JSON or raw view.','field-help'));return d;}for(const [k,v]of entries.slice(0,100)){if(budget.remaining<=0)break;d.append(tree(v,k,depth+1,budget));}if(entries.length>100||budget.remaining<=0)d.append(node('p','Display shortened. Use JSON or raw view for the complete response.','field-help'));return d;}
 function prettyJSON(data){const code=node('code'),text=JSON.stringify(data,null,2);if(text.length>200000){const wrapper=node('div');wrapper.append(node('p','Large response: syntax highlighting is disabled to keep the viewer responsive.','field-help'),node('pre',text,'json-pre'));return wrapper;}const re=/("(?:\\.|[^"\\])*"\s*:?)|\b(true|false|null)\b|(-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)/g;let offset=0,match;while((match=re.exec(text))){code.append(document.createTextNode(text.slice(offset,match.index)));code.append(node('span',match[0],match[1]?(match[0].endsWith(':')?'json-key':'json-string'):match[2]?'json-boolean':'json-number'));offset=re.lastIndex;}code.append(document.createTextNode(text.slice(offset)));const pre=node('pre',undefined,'json-pre');pre.append(code);return pre;}
 function renderResponse(){if(!responseData)return;const target=$('#response-content');target.replaceChildren();target.setAttribute('aria-labelledby','tab-'+view);const {text,data,isJSON,headers}=responseData;
  if(view==='headers'){target.append(node('p','Only headers exposed to browser JavaScript are shown.','field-help'));const dl=node('dl',undefined,'response-headers');for(const [k,v] of headers){dl.append(node('dt',k),node('dd',v));}target.append(dl);}
  else if(view==='raw')target.append(node('pre',text||'(Empty response body)','raw-response'));
  else if(!isJSON){target.append(node('p','This response is not JSON. Showing its text content.','field-help'),node('pre',text||'(Empty response body)','raw-response'));}
  else if(view==='tree')target.append(tree(data));
  else if(view==='pretty')target.append(prettyJSON(data));
  else if(view==='table'){const table=tableData(data);if(!table||!table.columns.length){target.append(node('p','No tabular records found. Try the tree or JSON view.'));return;}target.append(node('p',`${table.path} · Showing ${table.rows.length} of ${table.total} records · ${table.columns.length} columns maximum`,'field-help'));const wrap=node('div',undefined,'table-scroll'),el=node('table'),head=node('thead'),tr=node('tr');table.columns.forEach(k=>tr.append(node('th',k)));head.append(tr);el.append(head);const body=node('tbody');table.rows.forEach(r=>{const line=node('tr');table.columns.forEach(k=>{const v=r[k],text=typeof v==='object'?JSON.stringify(v):String(v??'');const cell=node('td',text.length>500?text.slice(0,500)+'…':text);line.append(cell);});body.append(line);});el.append(body);wrap.append(el);target.append(wrap);}
 }
 const tabs=[...root.querySelectorAll('[data-view]')];function selectTab(b){view=b.dataset.view;tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===b));t.tabIndex=t===b?0:-1;});renderResponse();}
 tabs.forEach((b,i)=>{b.addEventListener('click',()=>selectTab(b));b.addEventListener('keydown',ev=>{let n;if(ev.key==='ArrowRight')n=(i+1)%tabs.length;else if(ev.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(ev.key==='Home')n=0;else if(ev.key==='End')n=tabs.length-1;else return;ev.preventDefault();selectTab(tabs[n]);tabs[n].focus();});});
 $('#request-form').addEventListener('submit',async ev=>{
  ev.preventDefault();if(controller)return;$('#request-error').hidden=true;let req;try{req=buildRequest(input());}catch(error){$('#request-error').textContent=error.message;$('#request-error').hidden=false;return;}
  controller=new AbortController();const current=controller;timedOut=false;const start=performance.now();const timeout=setTimeout(()=>{timedOut=true;current.abort();},30000);
  $('#send-request').disabled=true;$('#send-request').textContent='Sending…';$('#cancel-request').hidden=false;$('#clear-request').disabled=true;$('#request-example').disabled=true;responseData=null;$('#download-response').disabled=true;$('#response-meta').replaceChildren(node('span','Request in progress…','status-pill'));$('#response-content').replaceChildren(node('p','Waiting for the provider…','field-help'));
  try{const response=await fetch(req.url,{...req.options,signal:current.signal});const result=await readLimited(response);let data,isJSON=false;try{data=JSON.parse(result.text);isJSON=true;}catch{}responseData={...result,data,isJSON,headers:[...response.headers],status:response.status};const elapsed=Math.round(performance.now()-start);$('#response-meta').replaceChildren(node('span',`${response.status} ${response.statusText||''}`,'status-pill '+(response.ok?'ok':'http-error')),node('span',`${elapsed.toLocaleString()} ms`),node('span',`${(result.bytes/1024).toFixed(1)} KB`));$('#download-response').disabled=false;renderResponse();}
  catch(error){const message=error.name==='AbortError'?(timedOut?'The request timed out after 30 seconds.':'Request cancelled.'):error instanceof TypeError?'The browser could not read the response. Possible causes include CORS, a network or TLS error, or a blocked redirect. Check the provider docs and your browser’s Network panel. A failed fetch does not prove the request had no effect.':error.message;$('#response-meta').replaceChildren(node('span','No readable response','status-pill http-error'));$('#response-content').replaceChildren(node('h3','Unable to display a response'),node('p',message),node('a','Read the CORS guide →'));$('#response-content a').href='/guides/browser-api-requests-and-cors/';}
  finally{clearTimeout(timeout);controller=null;$('#send-request').disabled=false;$('#send-request').textContent='Send request ↗';$('#cancel-request').hidden=true;$('#clear-request').disabled=false;$('#request-example').disabled=false;}
 });
 $('#cancel-request').addEventListener('click',()=>controller?.abort());
 $('#download-response').addEventListener('click',()=>{if(!responseData)return;const url=URL.createObjectURL(new Blob([responseData.text],{type:responseData.isJSON?'application/json':'text/plain'}));const a=document.createElement('a');a.href=url;a.download=responseData.isJSON?'api-response.json':'api-response.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 window.addEventListener('pagehide',()=>{controller?.abort();$('#request-form').reset();$('#request-url').value='';$('#request-params').replaceChildren();$('#request-headers').replaceChildren();$('#request-code').textContent='';$('#reveal-values').checked=false;codes=null;resetResponse();});
 loadExample(root.dataset.default);
}
